name: Build

on:
    workflow_dispatch:
    push:
    schedule:
        - cron: "0 1 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Setup Corepack
              run: corepack enable

            - name: Cache Yarn dependencies
              id: yarn-cache
              uses: actions/cache@v3
              with:
                  path: |
                      .yarn/cache
                      .yarn/unplugged
                      .yarn/install-state.gz
                      .pnp.cjs
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install Yarn dependencies
              run: yarn

            - name: Build
              run: yarn build

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: dist/*

            - name: Compress release
              run: |
                  pushd dist
                  tar -zcvf ../qqntim-build.tar.gz .
                  zip -r9 ../qqntim-build.zip .
                  popd

            - name: Get Date
              run: echo "date=$(date +%F)" >> $GITHUB_ENV

            - name: Create release
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      qqntim-build.tar.gz
                      qqntim-build.zip
                  tag_name: ${{ github.ref_name }}
                  prerelease: false
                  draft: false
                  name: ${{ github.ref_name }}

            - name: Create nightly release
              if: github.event_name == 'schedule'
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      qqntim-build.tar.gz
                      qqntim-build.zip
                  tag_name: nightly-${{ env.date }}
                  prerelease: true
                  draft: false
                  name: Nightly ${{ env.date }}
